/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  legaltextSidebar: [
    {
      type: 'doc',
      id: 'patent-law',
    },
    {
      type: 'doc',
      id: 'patent-regulations',
    },
    {
      type: 'doc',
      id: 'trademark-law',
    },
    {
      type: 'doc',
      id: 'trademark-regulations',
    },
    {
      type: 'doc',
      id: 'copyright-law',
    },
    {
      type: 'doc',
      id: 'copyright-regulations',
    },
    {
      type: 'doc',
      id: 'plant-protection-regulations',
    },
    {
      type: 'doc',
      id: 'pct',
    },
    {
      type: 'doc',
      id: 'agency-regulations',
    },
    {
      type: 'doc',
      id: 'agency-admin-measures',
    },
    {
      type: 'doc',
      id: 'admin-reconsider-law',
    },
    {
      type: 'doc',
      id: 'admin-procedure-law',
    },

  ],

};

export default sidebars;
